### ISSUE TITLE
Move non-secret config to govuk-puppet

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#136]
Some of our non-secret asset-manager configuration options (e.g. the `AWS_S3_BUCKET_NAME` environment variable) are currently set in govuk-secrets. This is unnecessary (because they're not secret) and makes them hard for us to change (because we don't have access to the secrets repo). We _think_ it's possible to move these config options to govuk-puppet which would allow us to change them when required.

## Todo

- [x] Ask someone to check that the values in my PR match those in govuk-secrets
- [x] Merge and deploy my PR
- [x] Ask someone to remove the equivalent values from govuk-secrets

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/6352 to move the S3 bucket name and region to govuk-puppet.

**Comment by chrisroos** [comment]
I've just merged the changes in https://github.com/alphagov/govuk-puppet/pull/6352 without first double checking that the values match those in govuk-secrets! I'll try to get someone to check the values now.

**Comment by chrisroos** [comment]
I've asked Paul B to check, and then remove, the equivalent settings in govuk-secrets.

**Comment by chrisroos** [comment]
Paul B has confirmed that the values in govuk-secrets matched those in https://github.com/alphagov/govuk-puppet/pull/6352. He's also opened https://github.com/alphagov/govuk-secrets/pull/39 to remove those values from govuk-secrets.

I don't think there's anything more I can do about this so I'm closing the issue.
