### ISSUE TITLE
Allow diversion of a percentage of traffic to the proxying to S3 solution

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#151]
We want to be able to set an environment variable to determine the percentage of traffic to use the proxying to S3 solution. The remaining traffic will be served via sendfile as before. This will allow us to gradually rollout the new solution while monitoring its effect on production load.

Note that the environment variable will need to be added to `govuk-puppet`. Ideally we'd like to be able to hard-code the value in different environments within that repo as per #136.

## Todo

- [x] Update asset-manager app
- [x] Update govuk-puppet
- [ ] Test the change on integration

**Comment by floehopper** [comment]
I'm un-assigning myself from this now that I've merged #152. I think the plan is that @chrisroos will pick up the `govuk-puppet` aspect of this issue.

**Comment by chrisroos** [comment]
I've opened a PR to add the environment variable to govuk-puppet - https://github.com/alphagov/govuk-puppet/pull/6351.

**Comment by chrisroos** [comment]
I've now merged the changes in https://github.com/alphagov/govuk-puppet/pull/6351. This should allow us to set the `PROXY_PERCENTAGE_OF_ASSET_REQUESTS_TO_S3_VIA_NGINX` environment variable to control the percentage of requests we respond to by serving assets hosted on S3.

**Comment by chrisroos** [comment]
I'm going to wait until the govuk-puppet change has been deployed to integration so that I can test this behaviour before closing the issue.

**Comment by chrisroos** [comment]
I've just tested this in integration and am confident that it's working as expected.

I manually modified the value in `/etc/govuk/asset-manager/env.d/PROXY_PERCENTAGE_OF_ASSET_REQUESTS_TO_S3_VIA_NGINX` and used the `deploy:with_hard_restart` Jenkins job to force a reload of asset-manager app. I uploaded a file to asset-manager and used `curl` to request that file from the Rails app directly (i.e. bypassing nginx).

With `PROXY_PERCENTAGE_OF_ASSET_REQUESTS_TO_S3_VIA_NGINX` set to 100, I saw that all responses contained the `X-Accel-Redirect` header instructing nginx to proxy the request to S3. 

With `PROXY_PERCENTAGE_OF_ASSET_REQUESTS_TO_S3_VIA_NGINX` set to 50, I saw that about 50% of the response included the `X-Accel-Redirect` header.
