### ISSUE TITLE
Work out how to measure the traffic being sent to S3 vs Nginx

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#162]
We'll want some way to measure the percentage of assets that are being served from S3 vs those being served from NFS. It might be that we already have sufficient logging in place to allow us to determine this split. If we don't then we should work out how best to do it. We might consider adding relevant logging or adding a custom HTTP header to tell the origin of the asset for a given request.

To date we've been relying on a difference in the value of the Etag headers (in combination with the use of the `proxy_to_s3_via_nginx` querystring) to know whether an asset was served from S3 or NFS. We're planning to bring the Etag (and all other) headers into line irrespective of where the asset was served from which will mean that we can no longer rely on this mechanism.

## Todo

- [x] Deploy to and test in integration
- [x] Deploy to and test in staging
- [x] Deploy to and test in production

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/6410 to add an HTTP header which tells us whether the asset is stored on S3 or NFS.

**Comment by chrisroos** [comment]
I've merged https://github.com/alphagov/govuk-puppet/pull/6410 and plan to test this on staging as soon as it's been deployed/applied.

**Comment by chrisroos** [comment]
I've tested this in integration and can confirm that I'm seeing the HTTP headers as expected:

```
$ curl https://assets-origin.integration.publishing.service.gov.uk/media/59ae7ce4e5274a5d5d9c81bf/2017-07-22-richmond-half-marathon-in-google-maps.png -v > /dev/null
< HTTP/1.1 200 OK
< GOVUK-Asset-Manager-File-Store: NFS

$ curl https://assets-origin.integration.publishing.service.gov.uk/media/59ae7ce4e5274a5d5d9c81bf/2017-07-22-richmond-half-marathon-in-google-maps.png?proxy_to_s3_via_nginx=true -v > /dev/null
< HTTP/1.1 200 OK
< GOVUK-Asset-Manager-File-Store: S3
```

I've also searched Kibana (using `@fields.govuk_asset_manager_file_store:S3`) and confirmed that the data is also showing up in the logs there.

**Comment by chrisroos** [comment]
The change in https://github.com/alphagov/govuk-puppet/pull/6410 has now been deployed to staging and production. I've confirmed that the HTTP header is present in both cases and that the value from the header is available in the Kibana logs.

**Comment by chrisroos** [comment]
I think this is all done so I'm marking this as done.
