### ISSUE TITLE
Respond with 404 if object doesn't exist on S3

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#176]
If we're trying to serve an asset from S3 and the underlying object doesn't exist, the response to the user will be a 403 Access Denied. We can observe the problem by requesting an object in production that doesn't yet exist on S3:

```
$ curl "https://assets.publishing.service.gov.uk/media/55bb5ed1ed915d1565000002/across-carriageway-stop-line-signals-or-police.jpg?proxy_to_s3_via_nginx=true" -v 
< HTTP/1.1 403 Forbidden
< Server: nginx
< Content-Type: application/xml
< Content-Disposition: inline; filename="across-carriageway-stop-line-signals-or-police.jpg"
< Cache-Control: max-age=86400, public
< Transfer-Encoding: chunked
< Accept-Ranges: bytes
< Date: Thu, 31 Aug 2017 11:43:21 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-lcy1143-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1504179801.099729,VS0,VE286
< 
<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host assets.publishing.service.gov.uk left intact
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>455AA7CADDC6A66A</RequestId><HostId>VBSlHKN8kW5D9SJiZri0XKoFN4wpRAzRaNyc18RLofiyHNIONJKNnQwvYojHr3FPmRpPeDPN2VI=</HostId></Error>
```

I came across this while investigating issue #139 and have created a new issue as it's a slightly different problem.

---

## Todo

- [ ] Deploy/run the changes in integration
- [ ] Deploy/run the changes in staging
- [ ] Deploy/run the changes in production

**Comment by chrisroos** [comment]
I'm going to take a look at this now.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-terraform-provisioning/pull/133 to update the asset-manager's IAM user's permission so that S3 responds with a 404 instead of a 403.

**Comment by chrisroos** [comment]
I've merged https://github.com/alphagov/govuk-terraform-provisioning/pull/133 and am going to ask someone to deploy/run the changes in integration/staging/production.

**Comment by chrisroos** [comment]
These changes have now been applied in integration, staging and production. I've confirmed that we're now seeing a 404 (instead of a 403) in those environments when an asset doesn't exist:

```
$ curl https://assets.publishing.service.gov.uk/media/55bb8be1ed915d1565000016/large-goods-vehicle-markings.jpg?proxy_to_s3_via_nginx=true -I
HTTP/1.1 404 Not Found
```

**Comment by chrisroos** [comment]
Note that the 404 response from S3 includes an XML body directly from AWS. We've created issue #178 to improve this situation.

I'm happy that this issue has been resolved so I'm closing it.
