### ISSUE TITLE
Save Whitehall image assets to Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#212]
We need to update Whitehall so that its image assets are being uploaded to Asset Manager instead of being saved to disk. We spiked on an approach to this in PR #185.

I can think of a couple of options to allow us to decouple this change from the change to nginx to start serving Whitehall images from Asset Manager (issue #214).

1. We could store new images using the standard Asset Manager endpoint which would mean these new assets will have slightly different URLs to existing assets.

2. We could store new images using the Asset Manager Whitehall endpoint which would mean new asset URLs match the format of existing asset URLs. Doing this is slightly more involved as it'll mean we have to switch the serving of Whitehall assets at the same time we deploy this change to the storage. Alternatively, we might be able to store these assets in Asset Manager and on disk which would allow us to continue serving them from disk in the short term until we're ready to switch the serving to Asset Manager.

## Tasks

- [x] Add CarrierWave storage engine to save files to Asset Manager
- [x] Update `LogoUploader` to save files to Asset Manager and NFS
- [x] Update `ConsultationResponseFormUploader ` to save files to Asset Manager and NFS
- [x] Update `ImageUploader` to save files to Asset Manager and NFS
- [x] Implement `#retrieve?`
- [x] Use version 49.3.1 of gds-api-adapters Gem to avoid the warnings `Content-Type` being overwritten warnings (depends on https://github.com/alphagov/gds-api-adapters/pull/759 being merged)
- [x] Set the `ASSET_MANAGER_BEARER_TOKEN` environment variable in Whitehall
  - [x] Add the environment variable to govuk-puppet (see https://github.com/alphagov/govuk-puppet/pull/6588)
  - [x] Grant Whitehall permission to Asset Manager in Signon
  - [x] Store application token from Signon in govuk-secrets
- [x] Rename `AssetManagerAndFileSystemStorage` to `AssetManagerAndQuarantinedFileStorage` to make it clearer that it wraps the existing `QuarantinedFileStorage`.
- [x] DRY up stubbing of Asset Manager API in the tests. There's duplication between the setup in features/support/asset_manager_helper.rb, test/test_helper.rb and test/unit/whitehall/publishing_api_test.rb.
- [x] Investigate stubbing `GdsApi::AssetManager` instead of using WebMock to stub requests to the API.
- [x] Add a feature flag to Whitehall (via an ENV variable) to allow this functionality to be turned on. It should be OFF by default.

**Comment by floehopper** [comment]
We should consider what happens if the Asset Manager API raises an exception or times out.

**Comment by chrisroos** [comment]
@floehopper, @chrislo and I have just chatted about the two options in the description and have agreed to go with option 2.

**Comment by chrisroos** [comment]
I've been digging through Whitehall to work out which models allow images to be uploaded.

## Whitehall models using the `ImageUploader`

* ClassificationFeaturingImageData
* Classification
* DefaultNewsOrganisationImageData
* Feature
* ImageData
* Person
* PromotionalFeatureItem
* TakePartPage

## Whitehall models with Images

These models all rely indirectly on the `ImageData` model from the list above.

* Announcement
  * FatalityNotice
  * Newsesque
    * NewsArticle
    * WorldLocationNewsArticle
  * Speech
* CaseStudy
* Consultation
* DetailedGuide
* Publication

**Comment by chrisroos** [comment]
I'm going to start working on this.

**Comment by chrisroos** [comment]
I've been looking into whether we need to support removal of assets from Asset Manager. I think the short answer is that we do if we want to give ourselves the best chance of keeping assets in sync between Whitehall and Asset Manager.

I came across https://github.com/alphagov/whitehall/pull/3162 which sets CarrierWave's `remove_previously_stored_files_after_update` setting to `false` on the `ImageUploader`. This explains why replacing some images (i.e. those uploaded using the `ImageUploader`) results the old image to remain on disk (see https://gist.github.com/chrisroos/1b83ca4867ca40001ecf5dc53b442247 for more). There's some info about this setting in https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Keep-uploaded-files-(for-a-specific-uploader). 

I've started to look at how CarrierWave implements file removal and, rather confusingly, it looks as though [it's on the Uploader](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/uploader/remove.rb#L11) and not on the Storage engine as I think I'd expect. I think it'd be worth understanding CarrierWave's behaviour when using the Fog storage engine with `remove_previously_stored_files_after_update` set to `true` (the default) as it's not clear to me that it'll actually delete files from the remote storage.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/whitehall/pull/3464 with my work in progress.

**Comment by chrisroos** [comment]
I've merged the change in https://github.com/alphagov/govuk-puppet/pull/6588 so that the `ASSET_MANAGER_BEARER_TOKEN` environment variable is being created for the Whitehall app.

I've also asked the following question in 2ndline:

> Howdi folks. We’re making changes to Whitehall so that it uploads its assets to Asset Manager. Can someone give the Whitehall API User in Signon access to Asset Manager, please? And can you also store the Access token for Asset Manager against `govuk::apps::whitehall::asset_manager_bearer_token` for integration/staging/production in govuk-secrets, please?

**Comment by chrisroos** [comment]
I've updated the todo list in the description based on our conversation, @chrislo and @floehopper. 

This is also a reminder that we discussed reducing the scope of the changes in https://github.com/alphagov/whitehall/pull/3464 by deploying them behind a feature flag.

**Comment by chrisroos** [comment]
@steventux has opened https://github.com/alphagov/govuk-secrets/pull/69 to set the `ASSET_MANAGER_BEARER_TOKEN` in the various environments.

**Comment by chrislo** [comment]
We've verified that the bearer token is configured correctly on integration by opening a rails console on `whitehall-backend-1` and running 

```
g = GdsApi::AssetManager.new(Plek.find('asset-manager'), bearer_token: ENV['ASSET_MANAGER_BEARER_TOKEN'])

g.asset(123)
#=> GdsApi::HTTPNotFound: URL: https://asset-manager.integration.publishing.service.gov.uk/assets/123
```

**Comment by chrislo** [comment]
We've removed two items from the todo list for this issue and created two new issues ⬆️
