### ISSUE TITLE
Change Whitehall so that it can remove non-attachment assets from Asset Manager

### ISSUE THREAD

**Issue by chrislo** [alphagov/asset-manager#244]
Arises from: #212 

Add the ability to remove images from Asset Manager when they're removed from the local file system in Whitehall. 

We have already established that we can use the existing Asset Manager `DELETE id` API endpoint to remove both Whitehall and mainstream assets in #226. 

## Tasks

- [x] Decide how to handle `USE_ASSET_MANAGER` feature flag for asset removal
  * We removed this feature flag in https://github.com/alphagov/whitehall/pull/3503
- [x] Update Whitehall to remove assets from Asset Manager when removed from Whitehall
  * This functionality was added in https://github.com/alphagov/whitehall/pull/3503

## Dependencies

- [x] Update Asset Manager to allow us to retrieve Whitehall Assets using their legacy URL path 
  * This functionality was added in https://github.com/alphagov/asset-manager/pull/264
- [x] Deploy Asset Manager to production
- [x] Update gds-api-adapters to allow us to retrieve Whitehall Assets using their legacy URL path 
  * This functionality was added in https://github.com/alphagov/gds-api-adapters/pull/764
- [x] Bump the version of the gds-api-adapters Gem
  * The version was bumped in https://github.com/alphagov/gds-api-adapters/pull/765
- [x] Update the version of gds-api-adapters being used in Whitehall
  * This was updated in https://github.com/alphagov/whitehall/pull/3503/

**Comment by chrisroos** [comment]
I'm going to start working on this.

**Comment by chrisroos** [comment]
@chrislo and I have made some good progress on this today. Our work is in the following branches:

* https://github.com/alphagov/asset-manager/tree/add-whitehall-asset-endpoint
* https://github.com/alphagov/gds-api-adapters/tree/add-whitehall-asset-endpoint
* https://github.com/alphagov/whitehall/tree/remove-assets-from-asset-manager
* https://github.com/alphagov/govuk-puppet/tree/use-asset-manager-from-whitehall

**Comment by chrisroos** [comment]
We've opened PR #264 to add the required functionality to Asset Manager.

**Comment by chrisroos** [comment]
I've opened PR https://github.com/alphagov/gds-api-adapters/pull/764 to add the required functionality to gds-api-adapters.

**Comment by chrisroos** [comment]
We opened https://github.com/alphagov/whitehall/pull/3503 to add the functionality for removing Whitehall assets from Asset Manager.

**Comment by chrisroos** [comment]
I'm closing this issue given that we're now removing Whitehall organisation logos from Asset Manager when they're removed from Whitehall.
