### ISSUE TITLE
Remove organisation logos from Whitehall asset folder on NFS

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#272]
We should remove the organisation logos from the NFS mount once we're confident that they're always being served from Asset Manager. This should help avoid any confusion about where the images are being stored.

## Todo

- [x] Merge https://github.com/alphagov/whitehall/pull/3552
- [x] Run `rake asset_manager:remove_organisation_logos` on integration and confirm that all organisation logos have been removed
- [x] Deploy Whitehall to staging
- [x] Run `rake asset_manager:remove_organisation_logos` on staging and confirm that all organisation logos have been removed
- [x] Deploy Whitehall to production
- [x] Run `rake asset_manager:remove_organisation_logos` on production and confirm that all organisation logos have been removed

**Comment by chrisroos** [comment]
We've opened https://github.com/alphagov/whitehall/pull/3552 to remove the organisation logos from NFS.

**Comment by chrisroos** [comment]
I'm going to get https://github.com/alphagov/whitehall/pull/3552 merged and deployed so that we can remove these organisation logos from the NFS mount.

**Comment by chrisroos** [comment]
I've deployed https://github.com/alphagov/whitehall/pull/3552 and have added a checklist of next steps to the description of this issue.

**Comment by chrislo** [comment]
alphagov/whitehall#3552  was part of `release_13117` which has been deployed to staging and production, so I'm going to check off those items.

**Comment by chrislo** [comment]
I [ran the rake task on integration](https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/3982/console) and confirmed that the directory is empty 

```
$ @integration-backend-1:~$ find /data/uploads/whitehall/clean/system/uploads/organisation/ -type f | wc -l
0
```

The output of the rake task is a little confusing as it refers to a directory which is a symlink to the mount 

```
17:09:47 Started by user Chris Lowis
17:09:47 [EnvInject] - Loading node environment variables.
17:09:47 Building in workspace /var/lib/jenkins/workspace/run-rake-task
17:09:47 [run-rake-task] $ /bin/sh -xe /tmp/hudson1961837225392622550.sh
17:09:47 + govuk_node_list -c whitehall_backend --single-node
17:09:47 + ssh deploy@whitehall-backend-2.backend.integration.publishing.service.gov.uk cd /var/apps/whitehall && govuk_setenv whitehall bundle exec rake asset_manager:remove_organisation_logos
17:09:52 I, [2017-12-14T17:09:51.865981 #22814]  INFO -- sentry: ** [Raven] Raven 2.6.3 ready to catch errors
17:09:58 /data/vhost/whitehall-admin.integration.publishing.service.gov.uk/releases/20171214101016/clean-uploads/system/uploads/organisation/logo/1067
17:09:58 /data/vhost/whitehall-admin.integration.publishing.service.gov.uk/releases/20171214101016/clean-uploads/system/uploads/organisation/logo/1067/UKTI_Education_logo_correct2.jpg
```

But it seems to have done the right thing, so perhaps we can improve the task output when we add tasks to delete other paths.

**Comment by chrisroos** [comment]
Thanks for picking this issue up, @chrislo :-)

**Comment by chrislo** [comment]
This task has been run by @tijmenb on Staging and Production. The rake task output had `106` files listed as deleted which matches the number expected in #341. Running the `find` command above showed that the files had been deleted from NFS. 

This task does leave an empty directory `/data/uploads/whitehall/clean/system/uploads/organisation`. I'm not quite sure whether it's worth cleaning those up. 

2MB down, ~700GB to go!
