### ISSUE TITLE
Serve Whitehall's promotional feature images from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#398]
This has been extracted from https://github.com/alphagov/asset-manager/issues/215 to make it easier to manage the remaining work. See that issue for lots more information.

Example asset: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg

## Todo

- [x] Run `asset_manager:migrate_assets[system/uploads/promotional_feature_item/image]` on production
- [x] Ask 2ndline to check the number of these assets on the filesystem vs the number in the Asset Manager database
- [x] Create PR in govuk-puppet to make the change
- [x] Merge https://github.com/alphagov/govuk-puppet/pull/7073
- [x] Check the effect of the PR in integration - ensure that these assets are now being served by Asset Manager
- [x] Deploy https://github.com/alphagov/govuk-puppet/pull/7073 to production

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7073 to update the nginx config to serve these assets from Asset Manager.

**Comment by chrisroos** [comment]
I ran the following commands in integration. We need to run the same commands in production to give us confidence that the Whitehall NFS mount and Asset Manager database are in sync before we switch the config:

```
$ find /data/uploads/whitehall/clean/system/uploads/promotional_feature_item/
image -type f | wc -l
441

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/promotional_feature_item/image/)).count
=> 371
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/promotional_feature_item/image/)).count
=> 0
```

**Comment by chrisroos** [comment]
@gpeng ran the above commands on production to compare the number of assets on the filesystem versus the database:

```
$ find /data/uploads/whitehall/clean/system/uploads/promotional_feature_item/image -type f | wc -l
371

irb> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/promotional_feature_item/image/)).count
371

irb> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/promotional_feature_item/image/)).count
0
```

The results give me confidence that it's OK to merge the nginx config change in https://github.com/alphagov/asset-manager/issues/398.

**Comment by chrisroos** [comment]
I made a request to integration for the example asset in the description so that I can compare the output once https://github.com/alphagov/govuk-puppet/pull/7073 has been deployed and run on integration:

```
$ curl -v https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg > 
/dev/null

< HTTP/2 200 
< date: Mon, 15 Jan 2018 16:18:04 GMT
< content-type: image/jpeg
< content-length: 49716
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="Transparency.jpg"
< etag: "576e8caf-c234"
< last-modified: Sat, 25 Jun 2016 13:52:47 GMT
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization
```

**Comment by chrisroos** [comment]
I've requested the example asset in the description now that the changes in https://github.com/alphagov/govuk-puppet/pull/7073 have been merged and applied in integration.

```
$ curl -v https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg > /dev/null

< HTTP/2 200 
< date: Mon, 15 Jan 2018 18:05:50 GMT
< content-type: image/jpeg
< content-length: 49716
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="Transparency.jpg"
< etag: "517e4f76-c234"
< last-modified: Mon, 29 Apr 2013 10:46:14 GMT
< strict-transport-security: max-age=31536000
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization
```

The presence of the `strict-transport-security` header gives me confidence that this is now being served be asset-manager. I've also checked Kibana and can see that the requests are going to asset-manager.

However, the difference in the value in `last-modified` dates has me a bit concerned so I'm going to investigate that further.

**Comment by chrisroos** [comment]
I've just investigated the difference in `last-modified` dates mentioned in the comment above. I requested the same asset in staging and production and can see that the `last-modifed` and `etag` headers match those in the response from integration _after_ updating nginx to serve the asset from asset-manager. As such, I'm happy that the difference is down to the out-of-date data we have on integration since the migration to AWS.

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg?CJR$RANDOM" > /dev/null

< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: image/jpeg
< Last-Modified: Mon, 29 Apr 2013 10:46:14 GMT
< Content-Disposition: inline; filename="Transparency.jpg"
< Cache-Control: max-age=14400, public
< ETag: "517e4f76-c234"
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 49716
< Accept-Ranges: bytes
< Date: Mon, 15 Jan 2018 18:19:12 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lhr6324-LHR
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1516040353.777690,VS0,VE105
```

**Comment by chrisroos** [comment]
This has now been deployed to production and I've confirmed that these assets are being served from Asset Manager:

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/promotional_feature_item/image/1/Transparency.jpg?CJR2002 HTTP/1.1
> Host: assets.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*

< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="Transparency.jpg"
< Cache-Control: max-age=14400, public
< ETag: "517e4f76-c234"
< Last-Modified: Mon, 29 Apr 2013 10:46:14 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 49716
< Accept-Ranges: bytes
< Date: Wed, 17 Jan 2018 13:26:21 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lcy19250-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1516195582.607683,VS0,VE296

# Kibana logs - searching for xxx
January 17th 2018, 13:26:21.657	 - 	 - 	asset-manager
January 17th 2018, 13:26:21.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:26:21.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:26:21.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:26:21.000	 - 	 - 	assets-origin.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:26:21.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
```

**Comment by chrisroos** [comment]
This is all done so I'm closing this issue.
