### ISSUE TITLE
Serve Whitehall's take part page images from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#399]
This has been extracted from https://github.com/alphagov/asset-manager/issues/215 to make it easier to manage the remaining work. See that issue for lots more information.

Example asset: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg

## Todo

- [x] Run `asset_manager:migrate_assets[system/uploads/take_part_page/image]` on production
- [x] Ensure the number of assets on the filesystem match the corresponding number in the Asset Manager database - Ask 2ndline to run the queries in production
- [x] Create PR in govuk-puppet to make the change
- [x] Merge https://github.com/alphagov/govuk-puppet/pull/7095
- [x] Check the effect of the PR in integration - ensure that these assets are now being served by Asset Manager
- [ ] Deploy https://github.com/alphagov/govuk-puppet/pull/7095 to production

**Comment by chrisroos** [comment]
I ran the following commands in integration. We need to run the same commands in production to give us confidence that the Whitehall NFS mount and Asset Manager database are in sync before we switch the config:

```
$ find /data/uploads/whitehall/clean/system/uploads/take_part_page/image -typ
e f | wc -l
147

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/take_part_page/image/)).count
=> 147
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/take_part_page/image/)).count
=> 0
```

**Comment by chrisroos** [comment]
@gpeng has run the commands above in production.

```
$ find /data/uploads/whitehall/clean/system/uploads/take_part_page/image -type f | wc -l
147

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/take_part_page/image/)).count
=> 147
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/take_part_page/image/)).count
=> 0
```

The number of files on the filesystem matches the number of assets in the database so we can make the relevant nginx change to serve these from Asset Manager.

**Comment by chrisroos** [comment]
I've requested the example asset in the description from integration and used Kibana to confirm that it was served by Whitehall.

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR18166 HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 16 Jan 2018 11:53:13 GMT
< content-type: image/jpeg
< content-length: 362024
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="BigTreePlant.jpg"
< etag: "57707b4e-58628"
< last-modified: Mon, 27 Jun 2016 01:03:10 GMT
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization

# Kibana logs - searching for CJR18166
January 16th 2018, 11:53:14.000	 - 	 - 	assets-origin-json.event.access
January 16th 2018, 11:53:13.869	 - 	 - 	whitehall
January 16th 2018, 11:53:13.000	 - 	 - 	whitehall-admin-json.event.access
January 16th 2018, 11:53:13.000	 - 	 - 	whitehall-frontend-json.event.access
```

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7095 to update the nginx config to serve these assets from Asset Manager.

**Comment by chrisroos** [comment]
I've merged https://github.com/alphagov/govuk-puppet/pull/7095 and will check it on integration once it's been deployed/applied.

**Comment by chrisroos** [comment]
I've made a request for the example asset in integration and confirmed that it's now being served by Asset Manager:

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR25352 HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 16 Jan 2018 17:07:44 GMT
< content-type: image/jpeg
< content-length: 362024
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="BigTreePlant.jpg"
< etag: "51795217-58628"
< last-modified: Thu, 25 Apr 2013 15:56:07 GMT
< strict-transport-security: max-age=31536000
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization

# Kibana logs - searching for CJR25352
January 16th 2018, 17:07:44.000	 - 	 - 	assets-origin-json.event.access
January 16th 2018, 17:07:44.000	 - 	 - 	static-json.event.access
January 16th 2018, 17:07:44.000	 - 	 - 	asset-manager-json.event.access
January 16th 2018, 17:07:43.923	 - 	 - 	asset-manager
```

**Comment by chrisroos** [comment]
This change has been deployed to production and I've just confirmed that these assets are now being served by Asset Manager:

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/take_part_page/image/1/BigTreePlant.jpg?CJR15528 HTTP/1.1
> Host: assets.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="BigTreePlant.jpg"
< Cache-Control: max-age=14400, public
< ETag: "51795217-58628"
< Last-Modified: Thu, 25 Apr 2013 15:56:07 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 362024
< Accept-Ranges: bytes
< Date: Wed, 17 Jan 2018 13:30:01 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lcy19221-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1516195801.347020,VS0,VE412

# Kibana logs - searching for CJR15528
January 17th 2018, 13:30:01.427	 - 	 - 	asset-manager
January 17th 2018, 13:30:01.000	 - 	 - 	assets-origin.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:30:01.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:30:01.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:30:01.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:30:01.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
```

**Comment by chrisroos** [comment]
This is all done so I'm closing this issue.
