### ISSUE TITLE
Serve Whitehall's default news organisation images from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#400]
This has been extracted from https://github.com/alphagov/asset-manager/issues/215 to make it easier to manage the remaining work. See that issue for lots more information.

Example asset: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/default_news_organisation_image_data/file/1/HMT_buiding_plaque.jpg

## Todo

- [x] Run `asset_manager:migrate_assets[system/uploads/default_news_organisation_image_data/file]` on production
- [x] Ensure the number of assets on the filesystem match the corresponding number in the Asset Manager database - Ask 2ndline to run the queries in production
- [x] Create PR in govuk-puppet to make the change
- [x] Merge https://github.com/alphagov/govuk-puppet/pull/7096
- [ ] Check the effect of the PR in integration - ensure that these assets are now being served by Asset Manager
- [ ] Deploy https://github.com/alphagov/govuk-puppet/pull/7096 to production

**Comment by chrisroos** [comment]
I ran the following commands in integration. We need to run the same commands in production to give us confidence that the Whitehall NFS mount and Asset Manager database are in sync before we switch the config:

```
$ find /data/uploads/whitehall/clean/system/uploads/default_news_organisation_image_data/file -type f | wc -l
1862

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/default_news_organisation_image_data/file/)).count
=> 1883
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/default_news_organisation_image_data/file/)).count
=> 0
```

**Comment by chrisroos** [comment]
@gpeng has run the commands above in production.

```
$ find /data/uploads/whitehall/clean/system/uploads/default_news_organisation_image_data/file -type f | wc -l
1883

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/default_news_organisation_image_data/file/)).count
=> 1883
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/default_news_organisation_image_data/file/)).count
=> 0
```

The number of files on the filesystem matches the number of assets in the database so we can make the relevant nginx change to serve these from Asset Manager.

**Comment by chrisroos** [comment]
I've requested the example asset in the description from integration and used Kibana to confirm that it was served by Whitehall.

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/default_news_organisation_image_data/file/1/HMT_buiding_plaque.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/default_news_organisation_image_data/file/1/HMT_buiding_plaque.jpg?CJR29536 HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 16 Jan 2018 11:58:30 GMT
< content-type: image/jpeg
< content-length: 245501
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="HMT_buiding_plaque.jpg"
< etag: "576fc6b6-3befd"
< last-modified: Sun, 26 Jun 2016 12:12:38 GMT
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization

# Kibana logs - searching for CJR29536
January 16th 2018, 11:59:12.000	 - 	 - 	assets-origin-json.event.access
January 16th 2018, 11:59:11.966	 - 	 - 	whitehall
January 16th 2018, 11:59:11.000	 - 	 - 	whitehall-admin-json.event.access
January 16th 2018, 11:59:11.000	 - 	 - 	whitehall-frontend-json.event.access
```

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7096/files to update the nginx config to serve these assets from Asset Manager.

**Comment by chrisroos** [comment]
I merged https://github.com/alphagov/govuk-puppet/pull/7096 yesterday.

**Comment by chrisroos** [comment]
The change in https://github.com/alphagov/govuk-puppet/pull/7096 has been deployed to production and I've confirmed that we're now serving these assets from Asset Manager:

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/default_news_organisation_image_data/file/1/HMT_buiding_plaque.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/default_news_organisation_image_data/file/1/HMT_buiding_plaque.jpg?CJR17262 HTTP/1.1
> Host: assets.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: image/jpeg
< Content-Disposition: inline; filename="HMT_buiding_plaque.jpg"
< Cache-Control: max-age=14400, public
< ETag: "516be278-3befd"
< Last-Modified: Mon, 15 Apr 2013 11:20:24 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 245501
< Accept-Ranges: bytes
< Date: Wed, 17 Jan 2018 13:32:04 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lcy19246-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1516195925.680299,VS0,VE303

# Kibana logs - searching for CJR17262
January 17th 2018, 13:32:04.767	 - 	 - 	asset-manager
January 17th 2018, 13:32:04.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:32:04.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:32:04.000	 - 	 - 	assets-origin.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:32:04.000	 - 	 - 	asset-manager.publishing.service.gov.uk-json.event.access
January 17th 2018, 13:32:04.000	 - 	 - 	static.publishing.service.gov.uk-json.event.access
```

**Comment by chrisroos** [comment]
This is all done so I'm closing this issue.
