### ISSUE TITLE
Serve Whitehall's images from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#404]
This has been extracted from https://github.com/alphagov/asset-manager/issues/215 to make it easier to manage the remaining work. See that issue for lots more information.

Example asset: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/99/TradingPlaces2.jpg

## Todo

- [x] Ensure Whitehall migrate_assets Rake task is resilient to application deployments #414
- [x] Run `asset_manager:migrate_assets[system/uploads/image_data/file]` on production
- [x] Ask 2ndline to check the number of these assets on the filesystem vs the number in the Asset Manager database
- [x] Create PR in govuk-puppet to make the change
- [ ] Check the effect of the PR in integration - ensure that these assets are now being served by Asset Manager

**Comment by chrisroos** [comment]
I ran the following commands in integration. We need to run the same commands in production to give us confidence that the Whitehall NFS mount and Asset Manager database are in sync before we switch the config:

```
$ find /data/uploads/whitehall/clean/system/uploads/image_data/file -type f | wc -l
511331

> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/image_data/file/)).count
=> 15843
> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/image_data/file/)).count
=> 1462
```

Note that these figures aren't necessarily realistic - it's the commands we're interested in.

**Comment by chrisroos** [comment]
I've requested the example asset in the description from integration and used Kibana to confirm that it was served by Whitehall.

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/99/TradingPlaces2.jpg?CJR$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/image_data/file/99/TradingPlaces2.jpg?CJR26351 HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 16 Jan 2018 12:06:14 GMT
< content-type: image/jpeg
< content-length: 37879
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="TradingPlaces2.jpg"
< etag: "576e8453-93f7"
< last-modified: Sat, 25 Jun 2016 13:17:07 GMT
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization

# Kibana logs - searching for CJR26351
January 16th 2018, 12:06:14.686	 - 	 - 	whitehall
January 16th 2018, 12:06:14.000	 - 	 - 	whitehall-admin-json.event.access
January 16th 2018, 12:06:14.000	 - 	 - 	assets-origin-json.event.access
January 16th 2018, 12:06:14.000	 - 	 - 	whitehall-frontend-json.event.access
```

**Comment by chrislo** [comment]
I asked @andrewgarner to run the rake task in production. The task enqueued `500731 files` at `15:39:39` today `2018-01-18`. 

I can see that the jobs have been added to the [`asset_migration` queue in grafana](https://grafana.publishing.service.gov.uk/dashboard/db/sidekiq-older-versions-of-govuk_sidekiq?refresh=1m&orgId=1&var-Application=whitehall&var-Queues=All&from=now-3h&to=now). The [asset manager queue](https://grafana.publishing.service.gov.uk/dashboard/file/deployment_asset-manager.json?refresh=5s&orgId=1&panelId=5&fullscreen&from=now-3h&to=now) is processing jobs at around 35 job/s. If it maintains this rate we might expect the migration to complete in around 4 hours (5000731 / 35 = 14306s ~= 4 hours).

**Comment by chrislo** [comment]
The `asset_migration` queue was empty by `17:32:15` on `2018-01-19`. In the end it took around 26 hours to process the 500k assets. 

The asset manager queue dashboard reports that jobs were being processed at between 36 job/s and 28 job/s during the migration. 

<img width="1119" alt="screen shot 2018-01-22 at 06 18 40" src="https://user-images.githubusercontent.com/16707/35218335-43f3833e-ff3c-11e7-94cb-16e62d64e578.png">

**Comment by chrislo** [comment]
@andrewgarner also ran the following commands on production

```
andrewgarner@production-whitehall-backend-1:~$ find /data/uploads/whitehall/clean/system/uploads/image_data/file -type f | wc -l
501158
```

```
andrewgarner@production-backend-1:~$ govuk_app_console asset-manager
irb(main):001:0> WhitehallAsset.where(legacy_url_path: %r(/government/uploads/system/uploads/image_data/file/)).count
=> 501186
irb(main):002:0> WhitehallAsset.deleted.where(legacy_url_path: %r(/government/uploads/system/uploads/image_data/file/)).count
=> 1686
```

**Comment by chrislo** [comment]
I asked @h-lame to help me run those commands again just to check

```

**Comment by chrislo** [comment]
I've requested an asset on integration

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/government/uploads/system/uploads/image_data/file/99/TradingPlaces2.jpg?CRL$RANDOM" > /dev/null

> GET /government/uploads/system/uploads/image_data/file/99/TradingPlaces2.jpg?CRL29789 HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< date: Mon, 22 Jan 2018 14:52:54 GMT
< content-type: image/jpeg
< content-length: 37879
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=14400, public
< content-disposition: inline; filename="TradingPlaces2.jpg"
< etag: "5097dd6e-93f7"
< last-modified: Mon, 05 Nov 2012 15:38:22 GMT
< strict-transport-security: max-age=31536000
< x-frame-options: SAMEORIGIN
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization
```

and can see in Kibana that the request hit asset manager instead of Whitehall

<img width="1033" alt="screen shot 2018-01-22 at 10 02 38" src="https://user-images.githubusercontent.com/16707/35227318-cba47b98-ff5b-11e7-9330-90f0f4608313.png">

I'm happy that the changes to puppet are working on Integration.
