### ISSUE TITLE
Remove Whitehall's non-attachment assets from NFS

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#405]
This has been extracted from https://github.com/alphagov/asset-manager/issues/215 to make it easier to manage the remaining work. See that issue for lots more information.

## Todo

- [ ] Switch `ImageUploader` to use `asset_manager` storage
- [ ] Remove system/uploads/promotional_feature_item/image
- [ ] Remove system/uploads/take_part_page/image
- [ ] Remove system/uploads/default_news_organisation_image_data/file
- [ ] Remove system/uploads/classification_featuring_image_data/file
- [ ] Remove system/uploads/person/image
- [ ] Remove system/uploads/feature/image
- [ ] Remove system/uploads/image_data/file

**Comment by chrislo** [comment]
The [rake task changes](https://github.com/alphagov/whitehall/pull/3731) have been deployed to production.

**Comment by chrislo** [comment]
We're running these rake tasks on production now.
