### ISSUE TITLE
Make draft-assets virtual host publicly accessible in integration

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#429]
## Prequisites

- [x] Authenticate requests for draft assets #432

## Tasks

- [x] Create DNS entries for the new virtual host so it is publicly accessible - https://github.com/alphagov/govuk-dns-config/pull/46
- [ ] Add draft-assets virtual host in all environments - https://github.com/alphagov/govuk-puppet/pull/7165

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-dns-config/pull/46 to add draft-assets to DNS.

**Comment by chrisroos** [comment]
I've asked for help with SSL/ELB in the reliability-engineering channel in Slack.

**Comment by chrisroos** [comment]
Based on conversation in reliability-engineering, it sounds as though I need to open a PR in https://github.com/alphagov/govuk-aws-data to add the draft-assets domain.

**Comment by floehopper** [comment]
@chrisroos: I wonder if we might need to create an ELB and a Route53 record in this file: https://github.com/alphagov/govuk-aws/blob/master/terraform/projects/app-draft-cache/main.tf

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-aws-data/pull/82 to add draft-assets to the integration environment.

**Comment by chrisroos** [comment]
The change in https://github.com/alphagov/govuk-dns-config/pull/46 has now been deployed and I can see that draft-assets.integration.publishing.service.gov.uk is being resolved to draft-cache as expected:

```
$ dig draft-assets.integration.publishing.service.gov.uk

; <<>> DiG 9.9.7-P3 <<>> draft-assets.integration.publishing.service.gov.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24216
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;draft-assets.integration.publishing.service.gov.uk. IN A

;; ANSWER SECTION:
draft-assets.integration.publishing.service.gov.uk. 38 IN CNAME	draft-origin.integration.govuk.digital.
draft-origin.integration.govuk.digital.	34 IN CNAME draft-cache.integration.govuk.digital.
draft-cache.integration.govuk.digital. 60 IN A	54.171.170.185
draft-cache.integration.govuk.digital. 60 IN A	54.77.195.72

;; Query time: 108 msec
;; SERVER: 192.168.101.1#53(192.168.101.1)
;; WHEN: Mon Jan 29 14:07:28 GMT 2018
;; MSG SIZE  rcvd: 189
```

I'm now uncertain about whether I need to make the change in https://github.com/alphagov/govuk-aws-data/pull/82.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7165 to add the draft-assets virtual host in integration, staging and production.

**Comment by chrisroos** [comment]
I've merged https://github.com/alphagov/govuk-puppet/pull/7165 so we should be able to test the new draft-assets host in integration within the next 30 minutes or so.

**Comment by chrisroos** [comment]
I've noticed that we're displaying the default "Welcome to nginx" page when requesting https://draft-assets.integration.publishing.service.gov.uk/. I'm going to fix that now.

**Comment by chrisroos** [comment]
I've opened https://github.com/alphagov/govuk-puppet/pull/7189 to avoid us rendering the default nginx welcome page.

**Comment by chrisroos** [comment]
The draft-assets host has been available in integration for a while, and I've confirmed that we're now responding with a 404 for requests to https://draft-assets.integration.publishing.service.gov.uk/.

This is all done so I'm closing this issue.
